name: Portfolio Deployment with Apache

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Apache Server
      run: |
        # Define variables
        SERVER_USER="ubuntu"
        SERVER_IP="44.206.252.243"
        REMOTE_DIR="/var/www/html"

        # Sync files to the server using rsync
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ ${SERVER_USER}@${SERVER_IP}:${REMOTE_DIR}

        # Set correct permissions
        ssh -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_IP} "sudo chown -R www-data:www-data ${REMOTE_DIR} && sudo chmod -R 755 ${REMOTE_DIR}"
