name: Portfolio Deployment with Apache

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install Apache and Deploy Files
      run: |
        # Define variables
        SERVER_USER="ubuntu"
        SERVER_IP="44.206.252.243"
        REMOTE_DIR="/var/www/html"
        
        # Install Apache if not installed (this will run only if needed)
        ssh -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_IP} "sudo apt-get update && sudo apt-get install -y apache2"

        # Start and enable Apache
        ssh -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_IP} "sudo systemctl enable apache2 && sudo systemctl start apache2"

        # Create the remote directory with correct permissions using sudo
        ssh -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_IP} "sudo mkdir -p ${REMOTE_DIR} && sudo chown -R ${SERVER_USER}:${SERVER_USER} ${REMOTE_DIR}"

        # Deploy files with rsync using sudo to ensure permission
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ ${SERVER_USER}@${SERVER_IP}:${REMOTE_DIR}

        # Set proper ownership for files to Apache (www-data) after deployment
        ssh -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_IP} "sudo chown -R www-data:www-data ${REMOTE_DIR} && sudo chmod -R 755 ${REMOTE_DIR}"
